AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '*.gem'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/rack-url-canonicalizer.rb'
